### ISSUE TITLE
Figure out why volumes are causing permissions issues

### ISSUE THREAD

**Issue by l3iggs** [l3iggs/docker-owncloud#23]
Using VOLUME lines in the docker file seems to mess up the permissions of the target directories, figure out why that is/how to solve it.

**Comment by cema-sp** [comment]
I found that:
- VOLUME ["/usr/share/webapps/owncloud/data"] - works fine with chmod -R 0750, chown -R 33:33
- VOLUME ["/etc/webapps/owncloud/config"] - works fine with chmod -R 0750, chown -R 33:33
- VOLUME ["/usr/share/webapps/owncloud/apps"] - causes errors
- VOLUME ["/https"] - must contain certificates, otherwise works incorrect

**Comment by l3iggs** [comment]
Thank you.
I'm not really seeing the benefits of putting these volume lines in the Dockerfile over having the user configure their volumes from the command line when they run `docker` to start the container, so I was thinking of leaving these lines out for now.
What do you think?

**Comment by cema-sp** [comment]
I agree about these lines and I think they should be left commented just to show ability and paths.
