### ISSUE TITLE
Cannot create /var/www/owncloud/data

### ISSUE THREAD

**Issue by Floyddotnet** [l3iggs/docker-owncloud#36]
I have try the following 2 commands to start the docker image but this doesn’t effect.

```
docker run --name oc -p 80:80 -p 443:443 -d -e TARGET_SUBDIR=/ 
-v /media/RAID/owncloud/data:/usr/share/webapps/owncloud/data 
-v /media/RAID/owncloud/config:/etc/webapps/owncloud/config 
-v /media/RAID/owncloud/db:/var/lib/mysql
l3iggs/owncloud
```

and another try with

```
docker run --name oc -p 80:80 -p 443:443 -d -e TARGET_SUBDIR=/ 
-v /media/RAID/owncloud/data:/var/www/owncloud/data 
-v /media/RAID/owncloud/config:/etc/webapps/owncloud/config 
-v /media/RAID/owncloud/db:/var/lib/mysql 
l3iggs/owncloud 
```

The different is in the first volumn parameter.

What do i'm wrong?

**Comment by Floyddotnet** [comment]
![startup screen](http://snag.gy/cfnmD.jpg)

**Comment by Floyddotnet** [comment]
/var/www doesn't exists

```
[root@dfe22829e3a0 /]# ls /var                  
cache  db  empty  games  lib  local  lock  log  mail  opt  run  spool  tmp

[root@dfe22829e3a0 /]# find -name owncloud
./usr/share/webapps/owncloud
./usr/share/licenses/owncloud
./etc/webapps/owncloud
```

**Comment by Floyddotnet** [comment]
If i start docker with the 2. command the directory exists and success full mapped to /media/RAID/owncloud/data ... 3 files created and i can create new files from bash inside the image. i try also chown -R 33:33 /var/www/owncloud but this also doesnt effect.

**Comment by Floyddotnet** [comment]
Dump from owncloud log:

`{"reqId":"EOvNjiDYHFj3VHTFX2eI","remoteAddr":"172.17.42.1","app":"PHP","message":"mkdir(): open_basedir restriction in effect. File(\/var\/www\/owncloud\/data) is not within the allowed path(s): (\/srv\/http\/:\/home\/:\/tmp\/:\/usr\/share\/pear\/:\/usr\/share\/webapps\/owncloud\/:\/etc\/webapps\/owncloud) at \/usr\/share\/webapps\/owncloud\/lib\/private\/setup.php#264","level":3,"time":"2015-07-27T21:43:47+00:00"}`

**Comment by l3iggs** [comment]
Thanks for reporting this. I'll start working on a fix immediately.
I assume this is somehow related to the fact that I recently upgraded ownCloud to 8.1

**Comment by l3iggs** [comment]
@Floyddotnet
I'm having trouble understanding your English. I honestly don't even really know what you're asking in your first post here. In any case, there does not seem to be any problem (in this regard) with this ownCloud image.

I don't know where you got your config.php file from and since you haven't provided it here, I assume that it's incompatible with this Arch Linux based container. Most obviously, your `datadirectory`variable in your config.php should probably point to where you've mapped your data file volume, i.e. `/usr/share/webapps/owncloud/data`. It looks like the error shows that it's set to `/var/www/owncloud/data`. 

There are likely other issues with your config.php file. At this point you should probably read about and understand all of the config parameters [on this page](https://doc.owncloud.org/server/8.1/admin_manual/configuration_server/config_sample_php_parameters.html) so that you can edit them properly. 

In case your permissions for the volumes you're trying to map there might also be wrong, see my wiki post [here](https://github.com/l3iggs/docker-owncloud/wiki/Store-your-data-outside-of-the-container) to set the proper permissions.

**Comment by Floyddotnet** [comment]
Ok, sorry for my English. I will try it again:

I start a complete new try. I clear all Folders in /media/RAID/owncloud, delete all docker images and pull a fresh copy of your docker image from the docker hub.

after the i run this commands:

```
sudo chmod -R 770 /media/RAID/owncloud
sudo chgrp -R 33 /media/RAID/owncloud

sudo docker run --name oc -p 80:80 -p 443:443 -d -e TARGET_SUBDIR=/ 
-v /media/RAID/owncloud/data:/usr/share/webapps/owncloud/data 
-v /media/RAID/owncloud/config:/etc/webapps/owncloud/config 
-v /media/RAID/owncloud/db:/var/lib/mysql
l3iggs/owncloud
```

Open a browser with the url "http://localhost" and get the described error (see the screenshot).

After then i connect to the bash insight the docker via:

```
sudo docker exec -i -t oc bash
```

and run the following commands with his outputs:

```
[root@dfe22829e3a0 /]# ls /var                  
cache  db  empty  games  lib  local  lock  log  mail  opt  run  spool  tmp

[root@dfe22829e3a0 /]# find -name owncloud
./usr/share/webapps/owncloud
./usr/share/licenses/owncloud
./etc/webapps/owncloud
```

You can see there is now /var/www directory insight the container.

My host is a Linux Mint 17.2 (Ubuntu 14.04 LTS) with Kernel 4.1.1

I hope I could eliminate all ambiguities and bring my problem understandable over.

**Comment by l3iggs** [comment]
This is not a bug with this project.

If you need support on how to use docker, ask your questions in #docker in freenode IRC.
If you need support on how to use owncloud, ask your questions in #owncloud in freenode IRC.

**Comment by Floyddotnet** [comment]
-Can you please give me a hint?-

Solved
