### ISSUE TITLE
.htaccess & settings retention

### ISSUE THREAD

**Issue by bobberb** [l3iggs/docker-owncloud#39]
Questions:

Is the .htaccess warning of a data exposure applicable to the docker container?

**Comment by l3iggs** [comment]
I'm not familiar with the warning you're referring to.

**Comment by l3iggs** [comment]
Closing this due to a lack of info.
Happy to reopen it if someone can show me exactly where this warning is.

**Comment by minorsecond** [comment]
I created an external directory for storing data, and followed the steps, including the permissions fixer script. Upon first load of OwnCloud, I get a warning that all my files may be accessible due to a .htaccess file that doesn't work. The .htaccess file in the data directory exists and has the same permissions as the other files.
