### ISSUE TITLE
Apache config brocken?

### ISSUE THREAD

**Issue by PeterVollmer** [l3iggs/docker-owncloud#40]
After updating I've got an empty filetree page. After trying a fresh instance same issue.
![screenshot_2015-08-14_08-02-07](https://cloud.githubusercontent.com/assets/604655/9268106/d3334b20-425a-11e5-9bc3-ad1ce791caa9.png)

**Comment by l3iggs** [comment]
Hmm. Sorry about that. Give me a few hours and I'll have a chance to look at this more closely.

**Comment by PeterVollmer** [comment]
thanks

**Comment by PeterVollmer** [comment]
Hi my analysis was wrong. There are problems when you to use volumes. If you don't use volumes it works but who wants this.

**Comment by sjwoodard** [comment]
+1

**Comment by l3iggs** [comment]
I suspect you've setup a volume with a permissions issue. If nobody provides exact steps I can take to recreate this problem, then I can't help you fix it.

**Comment by PeterVollmer** [comment]
Hi sorry for not writing 

the working work around I've found in the web was rerunning permission change(re set) on each start. Rerunning your script at each start has worked for me.

**Comment by l3iggs** [comment]
In summary:
If you attach a volume with incorrect permissions things break.
The solution is to make sure your attached volumes conform the the ownCloud permissions model as described here: https://doc.owncloud.org/server/8.2/admin_manual/installation/installation_wizard.html#strong-perms-label

You can force the permissions to be fixed by running the script provided in this image at `/root/fixPerms.sh` after you mount your volumes, but that's not really the "correct" way to fix this, instead fix your volume's permissions problem.
