### ISSUE TITLE
Not starting / cert generation issue...

### ISSUE THREAD

**Issue by LVLAaron** [l3iggs/docker-owncloud#51]
I install the container and cannot access the webui. 
I had to open the CLI for the docker image and run
'
[root@c4484faa4069 /]# apachectl start
AH00526: Syntax error on line 144 of /etc/httpd/conf/extra/httpd-ssl.conf:
SSLCertificateFile: file '/https/server.crt' does not exist or is empty

[root@c4484faa4069 /]# sh -c 'SUBJECT="/C=US/ST=CA/L=CITY/O=ORGANIZATION/OU=UNIT/CN=localhost" /etc/httpd/conf/genSSLKey.sh'  
[root@c4484faa4069 /]# cp /etc/httpd/conf/server.crt /https
[root@c4484faa4069 /]# cp /etc/httpd/conf/server.key /https
[root@c4484faa4069 /]#  apachectl restart
httpd not running, trying to start
'
Following that I am able to access the UI. 

Not sure it matters but this is being used on unRAID. Discussion here 
http://lime-technology.com/forum/index.php?topic=38930.msg427988#msg427988

**Comment by l3iggs** [comment]
Hmm. Thanks for the heads up. I will try to recreate this and get back to you.

**Comment by LVLAaron** [comment]
When I enter the webui after the above steps, I'm at the setup screen... I can select MySQL as the database but the credentials are unknown...

**Comment by l3iggs** [comment]
I'll ignore your MySQL comment for now. I can not recreate your issue. The server seems to be running fine. Are you following my usage instructions exactly as I've written them in the readme?: https://github.com/l3iggs/docker-owncloud#usage

**Comment by LVLAaron** [comment]
There isn't much that the user can screw up before the webui should be able to be displayed. This is the code the unraid executes to start the container. 

> root@localhost:# /usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d --name="owncloud" --net="bridge" -e TZ="America/New_York" -p 8443:443/tcp -p 8000:80/tcp -v "/mnt/cache/.docker_owncloud/data":"/usr/share/webapps/owncloud/data":rw -v "/mnt/cache/.docker_owncloud/config":"/usr/share/webapps/owncloud/config":rw -v "/mnt/cache/.docker_owncloud/certs":"/https":rw l3iggs/owncloud

**Comment by LVLAaron** [comment]
I installed from the CLI of unraid so it's not using any of the wrappers required... I can immediately get to the non-ssl site, but when going to the SSL site I get: 

Bad request!

Your browser (or proxy) sent a request that this server could not understand.

If you think this is a server error, please contact the webmaster.

Error 400

www.example.com
Apache/2.4.17 (Unix) OpenSSL/1.0.2e PHP/5.6.16

**Comment by l3iggs** [comment]
I'm not too familiar with unRaid or whatever environment you're running the docker server in. It appears to me that whoever has integrated my docker owncloud image into unraid has made some sort of mistake and I'm not really in the position to solve those kinds of problems.  It looks like the command you've pasted above is using volumes to re-map a bunch of important owncloud folders and I think that is really what's causing the issue here. 

Of relevance here, the command you've pasted there is asking docker to remap the /https folder in my image (which contains valid and working ssl certs) to some local folder: "/mnt/cache/.docker_owncloud/certs". Your error says that server.crt does not exist. I would bet that server.crt does not exist in /mnt/cache/.docker_owncloud/certs on the host (or it has the wrong permissions), which is why apache won't run.

**Comment by LVLAaron** [comment]
Loud and clear. What you're saying is the certs already exist but we're remapping that folder and that's what's causing breakage. Appreciate the help. I'll try it without mapping that volume and work with it on the unraid side of things.
