### ISSUE TITLE
Documents app needs to be updated

### ISSUE THREAD

**Issue by skidelo** [l3iggs/docker-owncloud#54]
The Documents app needs to be updated to version 0.11.0 in the docker container in order to open .doc/docx files.

Although the user can manually update it, might as well have it updated :-)

**Comment by l3iggs** [comment]
I agree.
I've been relying partially on the ownCloud packages in Arch Linux being properly maintained. Lately I'm considering re-packaging most oc related things myself partially because the Arch package maintainers seem slow and because I don't like some choices they've made in packaging things.
Stay tuned...

**Comment by greyltc** [comment]
I've stopped using Arch's crappy ownCloud package and repackaged it myself. All the apps should remain up to date now and several other issues are resolved by this.
