### ISSUE TITLE
is_dir(): open_basedir restriction in effect

### ISSUE THREAD

**Issue by jobski** [l3iggs/docker-owncloud#57]
Hi I am getting this error in the logs after upgrading to 8.2 

is_dir(): open_basedir restriction in effect. File(/usr/share/pear/) is not within the allowed path(s): (/srv/http/:/home/:/tmp/:/usr/share/pear/:/usr/share/webapps/owncloud/:/etc/webapps/owncloud:/dev/urandom) at /usr/share/webapps/owncloud/3rdparty/symfony/process/Symfony/Component/Process/ExecutableFinder.php#59

Not sure why this is happening, /usr/share/pear is already added to the open_basedir list as far as I can tell. Could you please advise?

**Comment by l3iggs** [comment]
I saw that too and I was confused as well. Is it actually causing any issue besides being a nuisance?

**Comment by jobski** [comment]
Glad to know its not just me. So far I don't think there's any impact on my usage. It could be an OC bug. 

Thanks for this OC image by the way!

**Comment by l3iggs** [comment]
No prob, I'm glad you're enjoying it!
I plan on making a few upgrades/improvements to the image in the not too distant future since plenty of people seem to be finding it useful.

**Comment by skidelo** [comment]
I3iggs, great job on this container!  Keep up the good work.
I have to manually add my external docker volume mounts to the open_basedir "allowed" list in /etc/httpd/conf/extra/owncloud.conf in order to mount them in owncloud.

I'm not sure of a good way around this... perhaps owncloud mountable paths could be passed in as an environmental variable and added via script?

**Comment by greyltc** [comment]
This issue is now resolved.
