### ISSUE TITLE
500 errors

### ISSUE THREAD

**Issue by greyltc** [l3iggs/docker-owncloud#69]
I've heard reports of users getting 500 errors with the container. I've never seen them myself. If someone could post some exact instructions on how to make them appear, then I can start to try to solve the problem.

**Comment by xogium** [comment]
Hi,
I've tried many things to get rid of those 500 error. I found that it's related to the config.php stuff and the database, and here's how to reproduce it:
1. create the directories that will be used as mount point for your owncloud data, owncloud config and mysql database on your host machine and set the correct permissions and group for them:
   sudo chgrp 33 {/path/to/owncloud/data,/path/to/owncloud/config}
   sudo chmod 0770 {/path/to/owncloud/data,/path/to/owncloud/config}
   sudo chgrp mysql /path/to/owncloud/database
   sudo chmod 0700 /path/to/owncloud/database
   Not sure if this part is required, but I've done it just in case
   sudo chown -R mysql:mysql /path/to/owncloud/database
2. use docker run like you would usually do, using a volume for /usr/share/webapps/owncloud/data, another for /usr/share/webapps/owncloud/config, and a final one for /var/lib/mysql/owncloud
3. follow the installation process and start uploading some content.
4. stop the oc container with docker stop oc
5. remove it with docker rm oc
6. now, reuse the same docker run command.
7. go on http://localhost/owncloud and enjoy that nice 500 internal error page, even if your database, config and data files aren't destroyed when the container is deleted.

At this point, you're stuck. You can't simply delete the config.php file and reinstall, because your database still exists, so the installation will fail. Your only choice is to delete both the database and config.php file and start all over again.

Note: Be doing this, since data are kept, if you recreate the same users, their files and other things will be added in a matter of minutes, but this is still an annoying 500 error issue.

**Comment by greyltc** [comment]
If this is really the only cause of the 500 errors, it's to be expected and there is no issue here. I've warned explicitly in the README.md that running `docker rm oc` destroys anything you have in the container:

>  #<--WARNING: this will delete anything stored inside the container

ownCloud can't be expected to work if suddenly its MySQL database disappears.

I can see the following solutions:
A) Don't run `docker rm oc`
or
B) use sqlite so that your database is in your data folder which you store outside and remap later
or
C) don't configure ownCloud to use the MySQL server in the container (use one outside the container instead)
or
D) figure out how to backup and restore your MySQL database. This page might be relevant here: https://doc.owncloud.org/server/8.2/admin_manual/maintenance/backup.html

**Comment by xogium** [comment]
The problem is.. Be doing that volume thing, I kept the subdir owncloud in mysql outside the container.. Or I didn't do that, or I don't get it.. I don,t understand where the problem can be if data, config and mysql database are saved outside...

Plus, when you try to reinstall with only the config.php file removed, owncloud refuses to install because the database already exists. So I don't get it

**Comment by greyltc** [comment]
Maybe the problem is that you're not putting the MySQL database properly back into the new container. I've never tried to reinsert a MySQL database back into the container.

`sudo chgrp mysql` is suspect because the GID you're setting there won't necessarily be the right one in the context of the container.
