### ISSUE TITLE
TARGET_SUBDIR=/ not working

### ISSUE THREAD

**Issue by nrgeen** [l3iggs/docker-owncloud#77]
Hello,

since the last update the environment variable "TARGET_SUBDIR=/" is no longer working.
There comes a 403 error message.

**Comment by splattner** [comment]
Same here!

I try to set TARGET_SUBDIR=/ but I get a 403 when trying to access my server. Without TARGET_SUBDIR access with the owncloud subdirectory works.

`Apache Log reports: [Wed Mar 16 18:19:29.500258 2016] [authz_core:error] [pid 84] [client 172.17.42.1:55818] AH01630: client denied by server configuration: /usr/share/webapps/owncloudindex.php`

so it seems that /usr/share/webapps/owncloudindex.php is being accessed rather than /usr/share/webapps/owncloud/index.php

**Comment by greyltc** [comment]
Sorry about that. The fixed image should be up in a few mins.
