### ISSUE TITLE
Login is broken :latest

### ISSUE THREAD

**Issue by nrgeen** [l3iggs/docker-owncloud#91]
Since today for me it's not possible to login. There is no error message. I use the image version "latest". If i switch to image version 9.0.1-1 it works.

**Comment by greyltc** [comment]
Thanks for your report. There does seem to be something wrong with `:latest` although I'm not sure what it is yet. Looking into it now...

**Comment by nrgeen** [comment]
Thanks for your great work!
For me 9.0.1-1 works actally fine.

**Comment by greyltc** [comment]
I _hope_ I've fixed it with [this commit](https://github.com/greyltc/docker-LAMP/commit/f68a3aded9cb5975f8c0bb9252cc7e8e51c42a66).

This change should take an hour or so to flow up to l3iggs/owncloud:latest before we can pull from the docker hub & test it properly.

**Comment by nrgeen** [comment]
Thanks. I'll test it.

**Comment by greyltc** [comment]
It doesn't seem to be fixed.
This seems to be a pretty nasty bug in an upstream package (owncloud/php):
https://github.com/owncloud/core/issues/24364
https://github.com/owncloud/core/pull/24343

I guess we need to complain there.

The reason you see it on :latest and not :9.0.1-1 is because 9.0.1-1 is on php 7.0.5-1 and :latest has the latest everything (php 7.0.6-3).

**Comment by greyltc** [comment]
I've applied a quick patch to fix this here because it's a showstopper and I'm not really sure how long it will be before there's a stable release upstream to fix it. The side effect of my fix is that ownCloud will warn you that someone (me) has mucked with its code.

You'll see a warning banner: "There were problems with the code integrity check. More information…"

`:latest` is working again for me now. @nrgeen please test it on your end and get back to me.

**Comment by nrgeen** [comment]
:latest work again for me too.
At the moment there are no errors or banners.
Thanks!

**Comment by rullzer** [comment]
https://github.com/owncloud/core/pull/24343 is merged.
