### ISSUE TITLE
failed integrity check

### ISSUE THREAD

**Issue by splattner** [l3iggs/docker-owncloud#92]
Since last update a get a integrity check failed error in Owncloud. Anybody else?

```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
    - INVALID_HASH
        - lib/private/appframework/http/request.php

Raw output
==========
Array
(
    [core] => Array
        (
            [INVALID_HASH] => Array
                (
                    [lib/private/appframework/http/request.php] => Array
                        (
                            [expected] => 385a45ae2cd3ccdd03e0465e1ee976530ce5a486d13603253f2fc45788f97f01bf0bd4e63e8153be3c2902326323a211851451fbb275202e262c1a9dcd0f5e0a
                            [current] => eab963c8c0b8cfa3728a2cd9aeaba2595c6d7bcd1d066f5198a744eaf9068e0c715a8652956b911dc279fbbb8c253b8711ae1c057c0f831bd97c74d5424fe083
                        )

                )

        )
)
```

**Comment by splattner** [comment]
according to #86 a fresh install of the image helped. 
On my site it doesn't.
I stopped and removed the docker container then pulled :latest and started again, but I still get this integrity check warning

**Comment by greyltc** [comment]
Hi @splattner have a look at [this comment](https://github.com/l3iggs/docker-owncloud/issues/91#issuecomment-216054065) and the issue there.

I've applied a "hack" fix to my container here to prevent a bug upstream( owncloud/core#24364
owncloud/core#24343 ) from making the image unusable.

The side effect is that you're seeing the security warning because I had to muck with OC's code to fix it.

**Comment by greyltc** [comment]
OC 9.0.2 came out a few days ago and I've just updated `:latest` to use that so hopefully the security warning will be gone now.
